---
- name: Ping k3s nodes
  hosts: k3s_nodes
  become: true

  tasks:
    - name: Update apt package
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade apt package
      ansible.builtin.apt:
        upgrade: dist

    - name: Remove unwanted dependencies
      ansible.builtin.apt:
        autoremove: yes
        purge: true

    - name: Clean cache
      ansible.builtin.apt:
        clean: yes
