apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: cluster-example
    namespace: psql
    labels:
        release: prometheus-community
spec:
    namespaceSelector:
        matchNames:
            - psql
    selector:
        matchLabels:
            cnpg.io/cluster: cluster-example
    podMetricsEndpoints:
        - port: metrics
          interval: 30s
