apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: glance
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/alsy4/alomalab.git
    targetRevision: kube
    path: kube/glance-dashboard
  destination:
    server: https://kubernetes.default.svc
    namespace: glance-dashboard
  syncPolicy:
    syncOptions:
      - createNamespace = true